version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-newsletter-command: &newsletter-cmd
  entrypoint: ["node_modules/.bin/basecms-newsletters"]
  command: ["dev", "index.js"]

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  GULP_POLLING_ENABLED: ${GULP_POLLING_ENABLED-0}
  GULP_POLLING_INTERVAL: ${GULP_POLLING_INTERVAL-1000}

x-env-tauron: &env-tauron
  GRAPHQL_URI: ${GRAPHQL_URI-https://tauron.graphql.base.parameter1.com}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  fcp:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/fcp
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 21094
      LIVERELOAD_PORT: 31094
      TENANT_KEY: acbm_fcp
    ports:
      - "21094:80"
      - "31094:31094"

volumes:
  yarn-cache: {}
