module.exports = {
  fcp: {
    brandName: 'For Construction Pros',
    logoSrc: '/files/base/acbm/fcp/image/static/fcp/logo.png',
    footerLogoSrc: '/files/base/acbm/fcp/image/static/newsletter/footer-fcp.jpeg',
    supportEmail: 'support@forconstructionpros.com',
    contactUsLink: 'https://www.forconstructionpros.com/contact-us',
    newsletterPrefLink: 'https://acbusiness.dragonforms.com/loading.do?omedasite=FCP_prefs_ProgReg',
    privacyPolicyLink: 'https://www.forconstructionpros.com/privacy-policy',
    socialMedia: {
      imagePath: '/files/base/acbm/fcp/image/static/newsletter',
      links: [
        { provider: 'facebook', href: 'https://www.facebook.com/ForConstructionPros' },
        { provider: 'linkedin', href: 'https://www.linkedin.com/company/forconstructionpros/' },
        { provider: 'twitter', href: 'https://twitter.com/4ConstructnPros' },
        { provider: 'instagram', href: 'https://www.instagram.com/4constructionpros/' },
        { provider: 'youtube', href: 'https://www.youtube.com/user/ForConstructionPros' },
      ],
    },
  },
  sso: {
    brandName: 'Safe & Secure Openings',
    logoSrc: '/files/base/acbm/fcp/image/static/sso/logo.png',
    socialMedia: {
      imagePath: '/files/base/acbm/fcp/image/static/newsletter',
      links: [
        { provider: 'facebook', href: 'https://www.facebook.com/fordsspros' },
        { provider: 'linkedin', href: 'https://www.linkedin.com/company/fordsspros/' },
        { provider: 'twitter', href: 'https://twitter.com/fordsspros' },
      ],
    },
  },
  pavementMagazine: {
    brandName: 'Pavement Management',
    footerLogoSrc: '/files/base/acbm/fcp/image/static/newsletter/footer-fcp.jpeg',
    primaryColor: '#ED1F24',
    supportEmail: 'support@forconstructionpros.com',
    contactUsLink: 'https://www.forconstructionpros.com/contact-us',
    newsletterPrefLink: 'https://acbusiness.dragonforms.com/loading.do?omedasite=FCP_prefs_ProgReg',
    privacyPolicyLink: 'https://www.forconstructionpros.com/privacy-policy',
    socialMedia: {
      imagePath: '/files/base/acbm/fcp/image/static/newsletter',
      links: [
        { provider: 'facebook', href: 'https://www.facebook.com/PavementMagazine' },
        { provider: 'linkedin', href: 'https://www.linkedin.com/company/pavement-maintenance-reconstruction-magazine/' },
        { provider: 'twitter', href: 'https://twitter.com/PavementMag' },
        { provider: 'instagram', href: 'https://www.instagram.com/pavementmagazine/' },
      ],
    },
  },
  equipmentToday: {
    brandName: 'Equipment Today',
    footerLogoSrc: '/files/base/acbm/fcp/image/static/newsletter/footer-fcp.jpeg',
    primaryColor: '#f89a00',
    supportEmail: 'support@forconstructionpros.com',
    contactUsLink: 'https://www.forconstructionpros.com/contact-us',
    newsletterPrefLink: 'https://acbusiness.dragonforms.com/loading.do?omedasite=FCP_prefs_ProgReg',
    privacyPolicyLink: 'https://www.forconstructionpros.com/privacy-policy',
    socialMedia: {
      imagePath: '/files/base/acbm/fcp/image/static/newsletter',
      links: [
        { provider: 'facebook', href: 'https://www.facebook.com/EquipmentToday' },
        { provider: 'linkedin', href: 'https://www.linkedin.com/company/equipment-today-magazine-official/' },
        { provider: 'twitter', href: 'https://twitter.com/EquipmentToday' },
        { provider: 'instagram', href: 'https://www.instagram.com/equipmenttoday/' },
        { provider: 'youtube', href: 'https://www.youtube.com/user/ForConstructionPros' },
      ],
    },
  },
  rentalMagazine: {
    brandName: 'Rental Magazine',
    footerLogoSrc: '/files/base/acbm/fcp/image/static/newsletter/footer-fcp.jpeg',
    supportEmail: 'support@forconstructionpros.com',
    contactUsLink: 'https://www.forconstructionpros.com/contact-us',
    newsletterPrefLink: 'https://acbusiness.dragonforms.com/loading.do?omedasite=FCP_prefs_ProgReg',
    privacyPolicyLink: 'https://www.forconstructionpros.com/privacy-policy',
    socialMedia: {
      imagePath: '/files/base/acbm/fcp/image/static/newsletter',
      links: [
        { provider: 'facebook', href: 'https://www.facebook.com/RentalMagazine' },
        { provider: 'linkedin', href: 'https://www.linkedin.com/company/rental-magazine/' },
        { provider: 'twitter', href: 'https://twitter.com/RentalPNI' },
        { provider: 'instagram', href: 'https://www.instagram.com/rentalpni/' },
      ],
    },
  },
  concreteContractor: {
    brandName: 'Concrete Contractor',
    footerLogoSrc: '/files/base/acbm/fcp/image/static/newsletter/footer-fcp.jpeg',
    primaryColor: '#ed1c24',
    supportEmail: 'support@forconstructionpros.com',
    contactUsLink: 'https://www.forconstructionpros.com/contact-us',
    newsletterPrefLink: 'https://acbusiness.dragonforms.com/loading.do?omedasite=FCP_prefs_ProgReg',
    privacyPolicyLink: 'https://www.forconstructionpros.com/privacy-policy',
    socialMedia: {
      imagePath: '/files/base/acbm/fcp/image/static/newsletter',
      links: [
        { provider: 'facebook', href: 'https://www.facebook.com/concretecontractor' },
        { provider: 'linkedin', href: 'https://www.linkedin.com/company/concrete-contractor-magazine/' },
        { provider: 'twitter', href: 'https://twitter.com/concreteinsider' },
        { provider: 'instagram', href: 'https://instagram.com/concretecontractor/' },
      ],
    },
  },
  asphaltContractor: {
    brandName: 'AsphaltContractor',
    footerLogoSrc: '/files/base/acbm/fcp/image/static/newsletter/footer-fcp.jpeg',
    primaryColor: '#f4381b',
    supportEmail: 'support@forconstructionpros.com',
    contactUsLink: 'https://www.forconstructionpros.com/contact-us',
    newsletterPrefLink: 'https://acbusiness.dragonforms.com/loading.do?omedasite=FCP_prefs_ProgReg',
    privacyPolicyLink: 'https://www.forconstructionpros.com/privacy-policy',
    socialMedia: {
      imagePath: '/files/base/acbm/fcp/image/static/newsletter',
      links: [
        { provider: 'facebook', href: 'https://www.facebook.com/Asphalt.Contractor/' },
        { provider: 'linkedin', href: 'https://www.linkedin.com/company/asphalt-contractor-magazine/' },
        { provider: 'twitter', href: 'https://twitter.com/AsphaltContrctr' },
        { provider: 'instagram', href: 'https://www.instagram.com/asphaltcontractor/' },
      ],
    },
  },
};
