const brands = require('./brands');
const emailX = require('./email-x');
// const nativeX = require('./native-x');

module.exports = {
  emailX,
  // nativeX,
  dpm: {
    emailx: {
      enabled: true,
    },
  },
  'asphalt-contractor-psc': {
    primaryColor: '#aa282e',
    name: 'Asphalt Contractor PSC',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2019/11/ACON_PSC_1.5ddec1344916c.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2019/11/ACON_PSC_2.5ddec13a9b99e.png',
  },
  'blacktop-update': {
    primaryColor: '#ED1F24',
    name: 'Blacktop Update',
    description: 'The latest news about paving, sweeing, striping and repairing pavements',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/PVM_BlacktopUpdate.5e94ce891774e.png',
    ...brands.pavementMagazine,
  },
  'breaking-ground': {
    primaryColor: '#f89a00',
    name: 'Breaking Ground',
    description: 'The latest equipment, business and fleet management tips to improve profitability',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/et_breaking_ground.5e9de70a6fe67.png',
    ...brands.equipmentToday,
  },
  'concrete-contractor-psc': {
    primaryColor: '#3432a9',
    name: 'Concrete Contractor PSC',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2021/04/cc_psc_left.608af211068ba.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2021/04/cc_psc_right.608af215924c4.png',
  },
  'constructing-green': {
    primaryColor: '#0A723B',
    name: 'Constructing Green',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2017/04/const_green_col1.58ebeba00b9f5.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2017/04/const_green_col2.58ebeba514558.png',
    ...brands.equipmentToday,
  },
  'construction-technology': {
    primaryColor: '#5DB2D7',
    name: 'Construction Technology',
    description: 'New ideas and opportunities to consider implementing in your business',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/FCP_CT.5e9f11b8164e9.png',
    ...brands.fcp,
  },
  'construction-workforce-management': {
    primaryColor: '#12b9ea',
    name: 'Construction Workforce Mangagement',
    description: 'Addressing key topics and critical issues centered around labor',
    headerLogoSrc: '/files/base/acbm/fcp/image/2021/05/PersonnelProgressENLHeader_630x100_v2_copy.609d806356884.png',
    ...brands.fcp,
  },
  'construction-zone-safety': {
    primaryColor: '#F04F23',
    name: 'Construction Zone Safety',
    description: 'Providing safety news, trends and insight for construction industry professionals',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/FCP_CZS.5e9dd61b5fe7e.png',
    ...brands.fcp,
  },
  'crane-connection': {
    primaryColor: '#e62725',
    name: 'Crane Connection',
    description: 'The Inside Scoop on the Crane Market',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/06/FCP_CraneConnection.5ef0c0889cb6c.png',
    ...brands.rentalMagazine,
  },
  'equipment-today-psc': {
    primaryColor: '#f8a11c',
    name: 'Equipment Today PSC',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2019/12/ET_PSC_1.5de54bbd50c12.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2019/12/ET_PSC_2.5de54bc48ddf3.png',
  },
  'fleet-maintenance-report': {
    primaryColor: '#f26522',
    name: 'Fleet Maintenance Report',
    headerLogoSrc: '/files/base/acbm/fcp/image/2021/03/FCP_Fleet_Maintenance.605893908c575.png',
  },
  'for-your-fleet': {
    primaryColor: '#e82f20',
    name: 'For Your Fleet',
    description: 'The leading source of product information and industry insight',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2017/04/for_your_fleet_col1.58ec185377cc8.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2017/04/for_your_fleet_col2.58ec186928eae.png',
    ...brands.rentalMagazine,
  },
  'headline-news': {
    primaryColor: '#f26522',
    name: 'Headline News',
    description: 'Insights, tips and news impacting the construction industry',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/FCP_HeadlineNews.5e875ac47444c.png',
    ...brands.fcp,
  },
  'in-the-mix': {
    primaryColor: '#ed1c24',
    name: 'In the Mix',
    description: 'Concrete industry topics that affect your business',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/07/CC_InTheMix.5f233b6338d4d.png',
    ...brands.concreteContractor,
  },
  'infrastructure-impact': {
    primaryColor: '#e9bf2f',
    name: 'Infrastructure Impact',
    headerLogoSrc: '/files/base/acbm/fcp/image/2021/06/fcp_header_InfraImpact.60d2476abb5d0.png',
    ...brands.fcp,
  },
  // eslint-disable-next-line quote-props
  'ipaf': {
    primaryColor: '#fdf21c',
    name: 'IPAF',
    description: 'News and updates on IPAF and the left equipment industry',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/IPAF.5e9f139b575c8.png',
    ...brands.fcp,
  },
  'lube-report': {
    primaryColor: '#0051FA',
    name: 'Lube Report',
    description: 'Best uses of oils, lubricants and greases for construction fleet maintenance',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/07/FCP_LubeReport.5f04942857891.png',
    ...brands.fcp,
  },
  'modern-fleet-management': {
    primaryColor: '#871937',
    name: 'Modern Fleet Management',
    description: 'Best practices, strategy and news to improve your fleet',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/FCP_ModernFleet.5e9dfa03a8258.png',
    ...brands.fcp,
  },
  'new-machine-solutions': {
    primaryColor: '#f87526',
    name: 'New Machine Solutions',
    description: 'The newest products and equipment for the construction market',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/FCP_NMS.5e948dd9b3cfa.png',
    ...brands.fcp,
  },
  'openings-news-views': {
    primaryColor: '#004f75',
    name: 'Openings News & Views',
    description: 'Exclusive insight into the most impactful news and trends shaping the non-residential door and hardware industry',
    headerLogoSrc: '/files/base/acbm/fcp/image/static/safesecure-enl-header.jpg',
    ...brands.sso,
  },
  'pavement-maintenance-reconstruction-psc': {
    primaryColor: '#d71921',
    name: 'Pavement Maintenance & Reconstruction PSC',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2019/11/PVM_PSC_1.5ddec3bbc35db.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2019/11/PVM_PSC_2.5ddec3c0b6633.png',
    ...brands.sso,
  },
  'power-rental': {
    primaryColor: '#fc501c',
    name: 'Power Rental',
    description: 'Product information and industry insight for the power rental equipment industry',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/RPN_PowerRental.5e94be6c618ce.png',
    ...brands.rentalMagazine,
  },
  'profit-matters': {
    primaryColor: '#f04200',
    name: 'Profit Matters',
    description: 'How to use technologies and strategies to improve construction profit',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2017/04/pm_col1.58ebdad143eb8.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2017/04/pm_col2.58ebdad6bf065.png',
    ...brands.rentalMagazine,
  },
  // eslint-disable-next-line quote-props
  'psc': {
    primaryColor: '#ecedee',
    name: 'Product Showcase',
    headerLogoSrc: '/files/base/acbm/fcp/image/2017/04/psc_col1.58ec27f92257f.png',
    ...brands.psc,
  },
  'rental-market-watch': {
    primaryColor: '#bb2b15',
    name: 'Rental Market Watch',
    description: 'Providing economic snapshots and industry trends to equipment rental professionals',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/RPN_RentalMarket.5e94b530b2698.png',
    ...brands.rentalMagazine,
  },
  'rental-psc': {
    primaryColor: '#f9a71e',
    name: 'Rental PSC',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2020/04/RPN_PSC_1.5eab10fd25630.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2020/11/RPN_PSC_OG.5fa957485b074.png',
    ...brands.rentalMagazine,
  },
  'rental-watch': {
    primaryColor: '#e62725',
    name: 'Rental Watch',
    description: 'Providing equipment rental professionals with the latest industry news, trends and insight',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/12/RPN_RentalWatch.5fcf921029822.png',
    ...brands.rentalMagazine,
  },
  'rental-weekly-recap': {
    primaryColor: '#e62725',
    name: 'Rental Weekly Recap',
    description: 'Providing eqipment renatal professionals with the latest industry news, trends and insight',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/11/RPN_WeeklyRecap.5f9c230a2f103.5fa1a9356e1a2.png',
    ...brands.rentalMagazine,
  },
  // 'resource-center-2': {
  //   name: 'Resource Center 2',
  //   headerLogoSrc: '/files/base/acbm/fcp/image/2017/04/resource_center_col1.58ec254138a79.png',
  // },
  'resource-center': {
    primaryColor: '#ecedee',
    name: 'Resource Center',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2017/04/resource_center_col1.58ec254138a79.png',
  },
  'road-building-update': {
    primaryColor: '#f4381b',
    name: 'Road Building Update',
    description: 'Insight into news and events specific to the highway construction community',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/AC_Roadbuilding.5e9df5f23513d.png',
    ...brands.asphaltContractor,
  },
  'show-product-showcase': {
    primaryColor: '#f8a11c',
    name: 'Show Product Showcase',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2019/12/Conexpo_PSC_1.5dfcf8e9d0e36.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2019/12/Conexpo_PSC_2.5dfcf8efb2ac7.png',
    ...brands.rentalMagazine,
  },
  'show-report-conexpo': {
    primaryColor: '#2783c2',
    name: 'Show Report ConExpo',
    description: 'News and products from the recent construction trade show',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/01/small_black_site_logo.5e1522fa71cb7.png',
    ...brands.fcp,
  },
  'show-report': {
    primaryColor: '#2783c2',
    name: 'Show Report',
    description: 'News and insights from World of Concrete',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/01/fcp_show_report.5e15eaa7decc9.png',
    ...brands.fcp,
  },
  'technology-trends': {
    primaryColor: '#F26522',
    name: 'Technology Trends',
    description: 'Daily headlines that impact construction',
    headerLogoSrcLeft: '/files/base/acbm/fcp/image/2017/04/technology_trends_col1.58ebf2d382d2d.png',
    headerLogoSrcRight: '/files/base/acbm/fcp/image/2017/04/technology_trends_col2.58ebf2d86c654.png',
    ...brands.fcp,
  },
  'the-contractors-best-friend-rewind': {
    primaryColor: '#1ECC9D',
    name: 'The Contractors Best Friend Rewind',
    description: 'Your personal resouce to improve management and business success',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/FCP_TCBFRewind.5e95f08a21b08.png',
    ...brands.fcp,
  },
  'the-contractors-best-friend': {
    primaryColor: '#108BC4',
    name: 'The Contractors Best Friend',
    description: 'Your personal resource to improve management and business success',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/FCP_TCBF.5e9daf22cb4e6.png',
    ...brands.fcp,
  },
  'truck-report': {
    primaryColor: '#ffa200',
    name: 'Truck Report',
    description: 'The latest truck innovations, product insights, selection and application tips',
    headerLogoSrc: '/files/base/acbm/fcp/image/2020/04/FCP_TruckReport.5e949f68b18af.png',
    ...brands.fcp,
  },
};
